version: '3.8'

services:
  # Define the MySQL service
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: releases_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  # Define the Node.js service
  app:
    build: .
    container_name: node-app
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mysql
      DB_USER: user
      DB_PASSWORD: password
      DB_DATABASE: releases_db
    depends_on:
      - mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
